### ISSUE TITLE
postgres 9.6 init configuration 

### ISSUE THREAD

**Issue by Burus** [cptactionhank/docker-atlassian-jira-software#18]
Thanks for your configuration example at first!

Did you ran jira-sw with new postgresql-9.6 configuration? I have problem with it and can't found resolution quickly. May be you can explain me sense of the error below?

I had tried to use different JDBC42 versions of new 9.4 postgres lib https://jdbc.postgresql.org/download.html 

```
2016-11-13 23:13:31,281 http-apr-8080-exec-2 ERROR      [o.a.c.c.C.[.[localhost].[/].[action]] Servlet.service() for servlet [action] in context with path [] threw exception
java.lang.UnsupportedOperationException: Not implemented for JIRA bootstrap time
	at com.atlassian.jira.security.login.BootstrapLoginManagerImpl.performElevatedSecurityCheck(BootstrapLoginManagerImpl.java:34)
	at com.atlassian.jira.security.login.JiraElevatedSecurityGuard.performElevatedSecurityCheck(JiraElevatedSecurityGuard.java:22)
	at com.atlassian.seraph.filter.PasswordBasedLoginFilter.runAuthentication(PasswordBasedLoginFilter.java:117)
	at com.atlassian.seraph.filter.PasswordBasedLoginFilter.login(PasswordBasedLoginFilter.java:78)
	at com.atlassian.seraph.filter.BaseLoginFilter.doFilter(BaseLoginFilter.java:110)
	... 22 filtered
	at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
	... 27 filtered
	at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
	... 26 filtered
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
2016-11-13 23:13:31,424 http-apr-8080-exec-2 INFO   -   [c.a.j.config.database.SystemDatabaseConfigurationLoader] Reading database configuration from /var/atlassian/jira/dbconfig.xml
2016-11-13 23:13:31,430 http-apr-8080-exec-2 INFO   -   [c.a.j.config.database.SystemDatabaseConfigurationLoader] Reading database configuration from /var/atlassian/jira/dbconfig.xml
2016-11-13 23:13:31,437 http-apr-8080-exec-2 ERROR   -   [500ErrorPage.cb2b2c99-5418-4811-8e64-8cfe29c0953b] Cannot render the 500 page
java.lang.NullPointerException
	at com.atlassian.jira.util.system.ExtendedSystemInfoUtilsImpl.getLogPath(ExtendedSystemInfoUtilsImpl.java:477)
	at com.atlassian.jira.web.util.InternalServerErrorDataSource.getFilePaths(InternalServerErrorDataSource.java:135)
	at com.atlassian.jira.web.util.InternalServerErrorDataSource.appendFullMessageData(InternalServerErrorDataSource.java:70)
	at com.atlassian.jira.web.servlet.InternalServerErrorHelper.dumpSoyDataToLog(InternalServerErrorHelper.java:114)
	at com.atlassian.jira.web.servlet.InternalServerErrorHelper.render(InternalServerErrorHelper.java:91)
	at com.atlassian.jira.web.servlet.InternalServerErrorHelper.render500ResponsePage(InternalServerErrorHelper.java:42)
	at com.atlassian.jira.web.servlet.InternalServerErrorServlet.doRequest(InternalServerErrorServlet.java:14)
	at com.atlassian.jira.web.servlet.InternalServerErrorServlet.doGet(InternalServerErrorServlet.java:20)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	... 59 filtered
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ghost** [comment]
How did you resolve this issue, @Burus ?

**Comment by cptactionhank** [comment]
The latest should work, now that i have updated the bundled PostgreSQL JDBC driver
