### ISSUE TITLE
Tempo plugin doesn't start after upgrade from 7.9.2 to 7.10.0

### ISSUE THREAD

**Issue by hlavki** [cptactionhank/docker-atlassian-jira-software#45]
Tempo plugin 8.11.0 doesn't start on jira startup, but when jira starts, then go to Administration -> System -> Manage Addons and manually enable Tempo Timesheets addon, then it starts and work properly.

```
2018-06-06 13:27:14,522 Spring DM Context Creation Timer WARN      [o.e.g.b.e.i.dependencies.startup.DependencyWaiterApplicationContextExecutor] Timeout occurred before finding service dependencies for [NonValidatingOsgiBundleXmlApplicationContext(bundle=com.tempoplugin.tempo-platform-jira, config=osgibundle:/META-INF/spring/*.xml)]
2018-06-06 13:27:14,610 Spring DM Context Creation Timer ERROR      [c.a.p.osgi.factory.OsgiPlugin] Plugin 'com.tempoplugin.tempo-platform-jira' never resolved service '&ao' with filter '(objectClass=com.atlassian.activeobjects.external.ActiveObjects)'
2018-06-06 13:27:14,678 Spring DM Context Creation Timer ERROR      [c.a.p.osgi.factory.OsgiPlugin] Unable to start the plugin container for plugin 'com.tempoplugin.tempo-platform-jira'
org.springframework.context.ApplicationContextException: Application context initialization for 'com.tempoplugin.tempo-platform-jira' has timed out waiting for (objectClass=com.atlassian.activeobjects.external.ActiveObjects)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:489)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:54)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:109)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
 
2018-06-06 13:27:15,097 Spring DM Context Creation Timer ERROR      [o.e.g.b.e.internal.support.ExtenderConfiguration] Application context refresh failed (NonValidatingOsgiBundleXmlApplicationContext(bundle=com.tempoplugin.tempo-platform-jira, config=osgibundle:/META-INF/spring/*.xml))
org.springframework.context.ApplicationContextException: Application context initialization for 'com.tempoplugin.tempo-platform-jira' has timed out waiting for (objectClass=com.atlassian.activeobjects.external.ActiveObjects)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:489)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:54)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:109)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2018-06-06 13:27:15,111 Spring DM Context Creation Timer ERROR      [o.e.g.b.e.i.dependencies.startup.DependencyWaiterApplicationContextExecutor] Unable to create application context for [com.tempoplugin.tempo-platform-jira], unsatisfied dependencies: Dependency on [(objectClass=com.atlassian.activeobjects.external.ActiveObjects)] (from bean [&ao])
org.springframework.context.ApplicationContextException: Application context initialization for 'com.tempoplugin.tempo-platform-jira' has timed out waiting for (objectClass=com.atlassian.activeobjects.external.ActiveObjects)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:489)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:54)
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:109)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2018-06-06 13:27:15,838 ThreadPoolAsyncTaskExecutor::Thread 17 DEBUG      [c.a.activeobjects.osgi.ActiveObjectsServiceFactory] afterPropertiesSet
```

**Comment by hlavki** [comment]
According to jira support had to mount custom `/opt/atlassian/jira/bin/setenv.sh` with:
```
JVM_SUPPORT_RECOMMENDED_ARGS="-Datlassian.plugins.enable.wait=300"
```
